# config/settings.yaml
spark:
  app_name: "analise-pedidos"

paths:
  pagamentos: "data/input/pagamentos"
  pedidos: "data/input/pedidos"
  output: "data/output/relatorio"

file_options:
  pedidos_csv:
    compression: "gzip"
    header: True
    sep: ";"

